if (FML.isModLoaded("MineFactoryReloaded")){
    NEI.hide("MineFactoryReloaded:machineblock");
    NEI.override("MineFactoryReloaded:machine.0",
        [9]
    );
    NEI.override("MineFactoryReloaded:machine.1",
        [3,7]
    );
    NEI.override("MineFactoryReloaded:machine.2",
        [0,1,4,6,11]
    );
    NEI.hide("MineFactoryReloaded:cable.plastic");
    NEI.hide("MineFactoryReloaded:cable.redstone");
    NEI.hide("MineFactoryReloaded:rednet.logic");
    NEI.hide("MineFactoryReloaded:rednet.panel");
    NEI.hide("MineFactoryReloaded:road");
    NEI.hide("MineFactoryReloaded:detcord");
    NEI.hide("MineFactoryReloaded:hammer");
    NEI.hide("MineFactoryReloaded:rednet.meter");
    NEI.hide("MineFactoryReloaded:rednet.memorycard");
    NEI.hide("MineFactoryReloaded:upgrade.logic");
    NEI.hide("MineFactoryReloaded:syringe.empty");
    NEI.hide("MineFactoryReloaded:syringe.health");
    NEI.hide("MineFactoryReloaded:syringe.growth");
    NEI.hide("MineFactoryReloaded:syringe.zombie");
    NEI.hide("MineFactoryReloaded:syringe.slime");
    NEI.hide("MineFactoryReloaded:syringe.cure");
    NEI.hide("MineFactoryReloaded:safarinet.launcher");
    NEI.hide("MineFactoryReloaded:safarinet.reusable");
    NEI.hide("MineFactoryReloaded:safarinet.singleuse");
    NEI.hide("MineFactoryReloaded:safarinet.jailer");
    NEI.hide("MineFactoryReloaded:safarinet.jailer.fancy");
    NEI.hide("MineFactoryReloaded:portaspawner");
    NEI.hide("MineFactoryReloaded:xpextractor");
    NEI.hide("MineFactoryReloaded:straw");
    NEI.hide("MineFactoryReloaded:plastic.cup");
    NEI.hide("MineFactoryReloaded:plastic.bag");
    NEI.hide("MineFactoryReloaded:fertilizer");
    NEI.hide("MineFactoryReloaded:fishingrod");
    NEI.hide("MineFactoryReloaded:needlegun.ammo.standard");
    NEI.hide("MineFactoryReloaded:needlegun.ammo.fire");
    NEI.hide("MineFactoryReloaded:needlegun.ammo.anvil");
    NEI.hide("MineFactoryReloaded:plastic.helm");
    NEI.hide("MineFactoryReloaded:plastic.chest");
    NEI.hide("MineFactoryReloaded:plastic.legs");
    NEI.hide("MineFactoryReloaded:plastic.boots");
}